### ISSUE TITLE
Malformed URL failed the deployment with a cryptic error message

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/cf-mysql-release#170]
I accidentally forgot the `https://` while filling out this [property](https://github.com/cloudfoundry/cf-mysql-release/blob/edf07ebb07fe261c890b48f7160b6219bd655932/jobs/cf-mysql-broker/spec#L41-L42) and the broker failed horribly with a super cryptic stack trace during the migration phase.

Redeploying with `https://` fixed the issue, but it took me a long time to debug that was the problem.

It would be awesome if that input was validated so that this doesn't happen when you make a simple mistake.

```
Migrations failed at Tue Jun 27 23:12:58 UTC 2017
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
mysql_broker already exists
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
TypeError: can't dup NilClass
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http/generic_request.rb:18:in `dup'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http/generic_request.rb:18:in `initialize'
/var/vcap/packages/ruby/lib/ruby/2.3.0/net/http/request.rb:15:in `initialize'
/var/vcap/data/packages/cf-mysql-broker/e5babc91a5ba10ba2ece69584076dee010f4af60/app/models/cloud_controller_http_client.rb:11:in `new'
/var/vcap/data/packages/cf-mysql-broker/e5babc91a5ba10ba2ece69584076dee010f4af60/app/models/cloud_controller_http_client.rb:11:in `get'
/var/vcap/data/packages/cf-mysql-broker/e5babc91a5ba10ba2ece69584076dee010f4af60/lib/configuration.rb:32:in `cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/e5babc91a5ba10ba2ece69584076dee010f4af60/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/e5babc91a5ba10ba2ece69584076dee010f4af60/config/initializers/omniauth.rb:10:in `block in <top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:6:in `initialize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/stack.rb:43:in `new'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/stack.rb:118:in `inject'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/stack.rb:118:in `build'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:502:in `app'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/var/vcap/packages/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/var/vcap/data/packages/cf-mysql-broker/e5babc91a5ba10ba2ece69584076dee010f4af60/config/environment.rb:5:in `<top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/var/vcap/packages/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/var/vcap/packages/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/var/vcap/packages/cf-mysql-broker/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<top (required)>'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/var/vcap/packages/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/var/vcap/packages/ruby/bin/bundle:22:in `load'
/var/vcap/packages/ruby/bin/bundle:22:in `<main>'
```

**Comment by bgandon** [comment]
+1
It would be nice to have a more explicit error message.
Hitting the same message, I figured the root cause out only because I found this issue report here.
